name       : colord-kde
version    : 23.04.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/colord-kde-23.04.3.tar.xz : e0cf5bf671e07e866c7ca13f2e0ca11a20b7a27608fdb3cca432e85a39ad16a6
homepage   : https://userbase.kde.org/Color_Management
license    :
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : Interfaces and session daemon to colord for KDE
description: |
    Interfaces and session daemon to colord for KDE
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(lcms2)
    - pkgconfig(xrandr)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpackage-devel
    - kwindowsystem-devel
rundeps    :
    - kirigami-addons
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
