name       : colord-kde
version    : 23.04.2
release    : 3
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/colord-kde-23.04.2.tar.xz : b81f99129e3a057225ba5f19988772ce3825fea2bd8e73700f7d48d9b31bb551
homepage   : https://userbase.kde.org/Color_Management
license    :
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : Interfaces and session daemon to colord for KDE
description: |
    Interfaces and session daemon to colord for KDE
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(lcms2)
    - pkgconfig(xrandr)
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kitemmodels-devel
    - kpackage-devel
    - kwindowsystem-devel
rundeps    :
    - kirigami-addons
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
